apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
spec:
  hard:
    pods: "4"
    requests.cpu: "500m"
    requests.memory: 1Gi
    requests.ephemeral-storage: 2Gi
    limits.cpu: "1"
    limits.memory: 2Gi
    limits.ephemeral-storage: 4Gi
